repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v1.19.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88, --ignore-unknown]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
        args: [--skip-string-normalization]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
